// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "DepthImage.h"

static int __DepthImage_hash_computed;
static uint64_t __DepthImage_hash;

uint64_t __DepthImage_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __DepthImage_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__DepthImage_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0xa726ea2957bb9d25LL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __DepthImage_get_hash(void)
{
    if (!__DepthImage_hash_computed) {
        __DepthImage_hash = (int64_t)__DepthImage_hash_recursive(NULL);
        __DepthImage_hash_computed = 1;
    }

    return __DepthImage_hash;
}

int __DepthImage_encode_array(void *buf, int offset, int maxlen, const DepthImage *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].line_stride), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].bytes_per_pixel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_bytes), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].pixel_data, p[element].num_bytes);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].meters_per_unit), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int DepthImage_encode(void *buf, int offset, int maxlen, const DepthImage *p)
{
    int pos = 0, thislen;
    int64_t hash = __DepthImage_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __DepthImage_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __DepthImage_encoded_array_size(const DepthImage *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int32_t_encoded_array_size(&(p[element].width), 1);

        size += __int32_t_encoded_array_size(&(p[element].height), 1);

        size += __int32_t_encoded_array_size(&(p[element].line_stride), 1);

        size += __int32_t_encoded_array_size(&(p[element].bytes_per_pixel), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_bytes), 1);

        size += __byte_encoded_array_size(p[element].pixel_data, p[element].num_bytes);

        size += __float_encoded_array_size(&(p[element].meters_per_unit), 1);

    }
    return size;
}

int DepthImage_encoded_size(const DepthImage *p)
{
    return 8 + __DepthImage_encoded_array_size(p, 1);
}

int __DepthImage_decode_array(const void *buf, int offset, int maxlen, DepthImage *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].line_stride), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].bytes_per_pixel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_bytes), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].pixel_data = (uint8_t*) lcm_malloc(sizeof(uint8_t) * p[element].num_bytes);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].pixel_data, p[element].num_bytes);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].meters_per_unit), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __DepthImage_decode_array_cleanup(DepthImage *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int32_t_decode_array_cleanup(&(p[element].width), 1);

        __int32_t_decode_array_cleanup(&(p[element].height), 1);

        __int32_t_decode_array_cleanup(&(p[element].line_stride), 1);

        __int32_t_decode_array_cleanup(&(p[element].bytes_per_pixel), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_bytes), 1);

        __byte_decode_array_cleanup(p[element].pixel_data, p[element].num_bytes);
        if (p[element].pixel_data) free(p[element].pixel_data);

        __float_decode_array_cleanup(&(p[element].meters_per_unit), 1);

    }
    return 0;
}

int DepthImage_decode(const void *buf, int offset, int maxlen, DepthImage *p)
{
    int pos = 0, thislen;
    int64_t hash = __DepthImage_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __DepthImage_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int DepthImage_decode_cleanup(DepthImage *p)
{
    return __DepthImage_decode_array_cleanup(p, 1);
}

int __DepthImage_clone_array(const DepthImage *p, DepthImage *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int32_t_clone_array(&(p[element].width), &(q[element].width), 1);

        __int32_t_clone_array(&(p[element].height), &(q[element].height), 1);

        __int32_t_clone_array(&(p[element].line_stride), &(q[element].line_stride), 1);

        __int32_t_clone_array(&(p[element].bytes_per_pixel), &(q[element].bytes_per_pixel), 1);

        __int32_t_clone_array(&(p[element].num_bytes), &(q[element].num_bytes), 1);

        q[element].pixel_data = (uint8_t*) lcm_malloc(sizeof(uint8_t) * q[element].num_bytes);
        __byte_clone_array(p[element].pixel_data, q[element].pixel_data, p[element].num_bytes);

        __float_clone_array(&(p[element].meters_per_unit), &(q[element].meters_per_unit), 1);

    }
    return 0;
}

DepthImage *DepthImage_copy(const DepthImage *p)
{
    DepthImage *q = (DepthImage*) malloc(sizeof(DepthImage));
    __DepthImage_clone_array(p, q, 1);
    return q;
}

void DepthImage_destroy(DepthImage *p)
{
    __DepthImage_decode_array_cleanup(p, 1);
    free(p);
}

int DepthImage_publish(lcm_t *lc, const char *channel, const DepthImage *p)
{
      int max_data_size = DepthImage_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = DepthImage_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _DepthImage_subscription_t {
    DepthImage_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void DepthImage_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    DepthImage p;
    memset(&p, 0, sizeof(DepthImage));
    status = DepthImage_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding DepthImage!!!\n", status);
        return;
    }

    DepthImage_subscription_t *h = (DepthImage_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    DepthImage_decode_cleanup (&p);
}

DepthImage_subscription_t* DepthImage_subscribe (lcm_t *lcm,
                    const char *channel,
                    DepthImage_handler_t f, void *userdata)
{
    DepthImage_subscription_t *n = (DepthImage_subscription_t*)
                       malloc(sizeof(DepthImage_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 DepthImage_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg DepthImage LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int DepthImage_subscription_set_queue_capacity (DepthImage_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int DepthImage_unsubscribe(lcm_t *lcm, DepthImage_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe DepthImage_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

